import { useMemo, useState } from 'react';
import { DataGrid } from '../components/DataGrid';
import { ExplanationSteps } from '../components/ExplanationSteps';
import { analyzeIPv4, parseCidr } from '../../domain/ip/ipv4';
import { analyzeIPv6 } from '../../domain/ip/ipv6';
import { equalSubnets, supernet, vlsm } from '../../domain/subnet/subnetting';
import { binaryExplanation, cidrExplanation, equalSubnetExplanation, ipv4Explanation, supernetExplanation, vlsmExplanation } from '../../domain/ip/explanations';

export function CalculatorSuite(){
  const [ip,setIp]=useState('192.168.10.20'); const [ipv6,setIpv6]=useState('2001:db8::1'); const [cidr,setCidr]=useState('192.168.10.20/27'); const [parent,setParent]=useState('10.0.0.0/24'); const [count,setCount]=useState(4); const [requirements,setRequirements]=useState('Web,60\nApp,90\nDB,25\nMgmt,10'); const [nets,setNets]=useState('10.0.0.0/24\n10.0.1.0/24\n10.0.2.0/24'); const [binaryValue,setBinaryValue]=useState('192.168.10.20');
  const ipv4Result=useMemo(()=>safe(()=>analyzeIPv4(ip)),[ip]); const ipv6Result=useMemo(()=>safe(()=>analyzeIPv6(ipv6)),[ipv6]); const cidrResult=useMemo(()=>safe(()=>parseCidr(cidr)),[cidr]); const subnets=useMemo(()=>safe(()=>equalSubnets(parent,count)),[parent,count]); const vlsmPlan=useMemo(()=>safe(()=>vlsm(parent, requirements.split('\n').map(l=>l.split(',')).filter(x=>x.length===2).map(([name,h])=>({name:name.trim(),hosts:Number(h)})))),[parent,requirements]); const summary=useMemo(()=>safe(()=>supernet(nets.split('\n').filter(Boolean))),[nets]);
  const ipExp=useMemo(()=>safe(()=>ipv4Explanation(ip)),[ip]); const cidrExp=useMemo(()=>safe(()=>cidrExplanation(cidr)),[cidr]); const subnetExp=useMemo(()=>safe(()=>equalSubnetExplanation(parent,count)),[parent,count]); const vlsmExp=useMemo(()=>safe(()=>vlsmExplanation(parent,requirements)),[parent,requirements]); const superExp=useMemo(()=>safe(()=>supernetExplanation(nets)),[nets]); const binExp=useMemo(()=>safe(()=>binaryExplanation(binaryValue)),[binaryValue]);
  return <div className="space-y-4">
    <Hero />
    <Panel title="Module 1 — IP Address Calculator" desc="Classify IPv4 and IPv6 addresses with decimal, binary, hexadecimal, octal, RFC and usability context."><div className="grid gap-3 lg:grid-cols-2"><div><label>IPv4</label><input className="input" value={ip} onChange={e=>setIp(e.target.value)}/>{render(ipv4Result)}{ipExp.ok&&<ExplanationSteps steps={ipExp.value}/>}</div><div><label>IPv6</label><input className="input" value={ipv6} onChange={e=>setIpv6(e.target.value)}/>{render(ipv6Result)}<div className="mt-4 rounded-xl bg-white/10 p-3 text-sm text-slate-300"><b>Simple IPv6 explanation:</b> IPv6 uses 8 groups of hexadecimal numbers. Each group is 16 bits. The app expands short form like <span className="font-mono">2001:db8::1</span> into all 8 groups, then checks special ranges like documentation, link-local, loopback and multicast.</div></div></div></Panel>
    <Panel title="Module 2 — CIDR Calculator" desc="Calculate network, broadcast, masks, host range, gateway and bit boundaries."><input className="input max-w-md" value={cidr} onChange={e=>setCidr(e.target.value)}/>{render(cidrResult)}{cidrResult.ok&&<BitBoundary bits={cidrResult.value.bitBoundary}/>} {cidrExp.ok&&<ExplanationSteps steps={cidrExp.value}/>}</Panel>
    <Panel title="Module 3 — Equal Subnet Calculator" desc="Split one network into equal-size subnets and show the arithmetic."><div className="grid gap-4 lg:grid-cols-2"><div><label>Parent CIDR</label><input className="input" value={parent} onChange={e=>setParent(e.target.value)}/><label>Equal subnet count</label><input className="input" type="number" value={count} onChange={e=>setCount(Number(e.target.value))}/>{subnets.ok?<Table rows={subnets.value.map(s=>({cidr:s.cidr, usable:s.usable, gateway:s.gateway, broadcast:s.broadcast}))}/>:<ErrorMsg msg={subnets.error}/>}</div><div>{subnetExp.ok&&<ExplanationSteps steps={subnetExp.value}/>}</div></div></Panel>
    <Panel title="Module 4 — VLSM Calculator" desc="Create a host-optimized subnet plan with waste analysis."><div className="grid gap-4 lg:grid-cols-2"><div><label>VLSM requirements: Department,Hosts</label><textarea className="input min-h-36" value={requirements} onChange={e=>setRequirements(e.target.value)}/>{vlsmPlan.ok?<Table rows={vlsmPlan.value.map(p=>({name:p.name, required:p.requiredHosts, cidr:p.block.cidr, usable:p.block.usable, waste:p.waste, gateway:p.gateway}))}/>:<ErrorMsg msg={vlsmPlan.error}/>}</div><div>{vlsmExp.ok&&<ExplanationSteps steps={vlsmExp.value}/>}</div></div></Panel>
    <Panel title="Module 5 — Supernet Calculator" desc="Merge CIDRs into a summary route and explain common-prefix arithmetic."><textarea className="input min-h-24 max-w-xl" value={nets} onChange={e=>setNets(e.target.value)}/>{summary.ok?<DataGrid rows={{summaryRoute:summary.value.cidr, network:summary.value.network, broadcast:summary.value.broadcast, mask:summary.value.subnetMask, binary:summary.value.binaryNetwork}}/>:<ErrorMsg msg={summary.error}/>} {superExp.ok&&<ExplanationSteps steps={superExp.value}/>}</Panel>
    <Panel title="Module 6 — Binary Calculator" desc="Convert decimal/IP value to binary, hexadecimal and octal with simple arithmetic meaning."><input className="input max-w-md" value={binaryValue} onChange={e=>setBinaryValue(e.target.value)}/>{binExp.ok?<ExplanationSteps steps={binExp.value}/>:<ErrorMsg msg={binExp.error}/>}</Panel>
  </div>
}
function Hero(){return <div className="card overflow-hidden p-6"><div className="max-w-4xl"><p className="badge w-fit">Interactive production architecture scaffold</p><h2 className="mt-3 text-3xl font-black md:text-5xl">A Cloudcraft + Packet Tracer inspired networking lab.</h2><p className="mt-3 text-slate-300">Modules 1 to 6 now show inner arithmetic calculations and very simple explanations for beginners.</p></div></div>}
function Panel({title,desc,children}:{title:string;desc:string;children:React.ReactNode}){return <section className="card p-5"><h3 className="text-xl font-bold">{title}</h3><p className="mb-4 text-sm text-slate-400">{desc}</p>{children}</section>}
function safe<T>(fn:()=>T):{ok:true;value:T}|{ok:false;error:string}{try{return{ok:true,value:fn()}}catch(e){return{ok:false,error:(e as Error).message}}}
function render<T extends object>(r:{ok:true;value:T}|{ok:false;error:string}){return r.ok?<div className="mt-3"><DataGrid rows={r.value as Record<string, unknown>}/></div>:<ErrorMsg msg={r.error}/>}
function ErrorMsg({msg}:{msg:string}){return <div className="mt-3 rounded-xl border border-bad/30 bg-bad/10 p-3 text-sm text-rose-100">{msg}</div>}
function Table({rows}:{rows:Record<string,unknown>[]}){return <div className="mt-3 overflow-auto rounded-xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/10 text-slate-300"><tr>{Object.keys(rows[0]??{}).map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-white/10">{Object.values(r).map((v,j)=><td className="p-2 font-mono" key={j}>{String(v)}</td>)}</tr>)}</tbody></table></div>}
function BitBoundary({bits}:{bits:string}){return <div className="mt-4 flex flex-wrap gap-1 font-mono text-xs">{bits.replaceAll('.','').split('').map((b:string,i:number)=><span key={i} className={`rounded px-1.5 py-1 ${b==='n'?'bg-cyanx/20 text-cyan-100':'bg-vio/20 text-violet-100'}`}>{b}</span>)}</div>}
